# Generated by Django 5.0.6 on 2024-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0004_recipe_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.TextField(default='[]'),
        ),
    ]
